---
deployment:
  tasks:
    - export DEPLOYPATH=/home/players/public_html/
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R w $DEPLOYPATH
