---
deployment:
      tasks:
        - export DEPLOYPATH=/home/players/public_html  # Add /<app_folder> if required
        - /bin cp -r img $DEPLOYPATH               
        - /bin cp -r js $DEPLOYPATH 
        - /bin cp -r inc $DEPLOYPATH 
        - /bin cp -r img $DEPLOYPATH 
        - /bin cp *.php $DEPLOYPATH 
        - /bin cp *.shtml $DEPLOYPATH 
        - /bin cp *.png $DEPLOYPATH 
        - /bin cp *.xml $DEPLOYPATH 
        - /bin cp *.ico $DEPLOYPATH 
        - /bin cp *.txt $DEPLOYPATH 
        - /bin cp *.svg $DEPLOYPATH 
